### ISSUE TITLE
Missing rights? Bootstrap isn't displayed properly.

### ISSUE THREAD

**Issue by xshadow** [beli3ver/Prosody-Web-Registration-Theme#2]
I followed the installation instructions for this beautiful theme. Thank you. 

But the bootstrap layout is not displayed. The arrows to select the correct number are visible and the you-haven't-filled-in-anything-handler is properly executed.

Do I need specific rights? Do you have any hints?

**Comment by beli3ver** [comment]
What does your prosody log said?
Show me the rights of the folder, and the config please.

**Comment by xshadow** [comment]
My configuration seems to be a little picky. It only works if I enable it above: 

> ------ Components ------

chapter. Works now
